version: "3"
services:
  springboot-layui:
    image: maven:3-jdk-8
    container_name: springboot-layui
    hostname: springboot-layui
    #network_mode: host
    ports:
      - "88:88"
    volumes:
      - /Users/admin2/Downloads/SpringBoot:/Users/admin2/Downloads/SpringBoot
      - /Users/admin2/.m2:/root/.m2
    working_dir: /Users/admin2/Downloads/SpringBoot/springboot-thymeleaf
    #working_dir: ../SpringBoot/springboot-thymeleaf
    command: ["/bin/sh", "-c", "mvn clean spring-boot:run"]