version: "3"
services:
  springboot-all:
    image: maven:3-jdk-8
    container_name: springboot-all
    hostname: springboot-all
    network_mode: bridge
    external_links:
      - mysql-compose:mysql-compose
      - redis-compose:redis-compose
    ports:
      - "8400:8400"
    volumes:
      - /Users/admin2/Downloads/SpringBoot:/Users/admin2/Downloads/SpringBoot
      - /Users/admin2/.m2:/root/.m2
    working_dir: /Users/admin2/Downloads/SpringBoot/springboot-redis-cache
    command: ["/bin/sh", "-c", "mvn clean spring-boot:run"]
